from Fila import Fila


fila = Fila()
fila.adicionar("d4")
fila.imprimir()
fila.adicionar("d8")
fila.imprimir()
fila.adicionar("d8")
fila.imprimir()
fila.adicionar("d10")
fila.imprimir()
fila.adicionar("d12")
fila.imprimir()
fila.adicionar("d20")
fila.imprimir()

fila.remover()
fila.imprimir()
fila.remover()
fila.imprimir()
fila.remover()
fila.imprimir()
fila.remover()
fila.imprimir()
fila.remover()
fila.imprimir()
fila.remover()
fila.imprimir()